# 异常

Dart 代码可以抛出并捕获异常。异常是指发生意外事件的错误说明。如果异常没有被捕获，则会暂停引发的异常，并且终止程序。

与 Java 相比，Dart 的所有异常都是未经检查的异常。方法不会声明它们可能引发的异常，并且不需要捕获任何异常。Dart 提供了 `Exception` 和 `Error` 类型，以及许多的预定义子类型。也可以自定义异常。Dart 程序可以抛出任何非 null 对象——不仅仅是 Exception 和 Error 对象——作为异常。

## throw

抛出异常。

```dart
throw FormatException('Expected at least 1 section');
```

也可以抛出任何对象。

```dart
throw 'Out of llamas!';
```

> 注意：生产代码通常会抛出实现 `Error` 或者 `Exception` 的类型。

因为抛出异常是一个表达式，因此可以在 => 以及任何允许语句的地方使用。

```dart
void distanceTo(Point other) => throw UnimplementedError();
```

## catch

捕获异常会阻止异常的传播，除非重新抛出一个异常。捕获异常能够有机会处理它。

```dart
try {
  breedMoreLlamas();
} on OutOfLlamasException {
  buyMoreLlamas();
}
```

要处理可能抛出多种类型异常的代码，可以使用多个 catch 子句。与抛出对象类型匹配的第一个 catch 子句会处理异常。如果 catch 子句未指定类型，则该子句可以处理任何类型的异常对象。

```dart
try {
  breedMoreLlamas();
} on OutOfLlamasException {
  // A specific exception
  buyMoreLlamas();
} on Exception catch (e) {
  // Anything else that is an exception
  print('Unknown exception: $e');
} catch (e) {
  // No specified type, handles all
  print('Something really unknown: $e');
}
```

可以使用 `on` 或者 `catch` 或者两个结合使用。需要指定异常类型是使用 `on` 。当异常处理需要用到异常对象是使用 `catch` 。

你可以给 `catch()` 指定一个或者两个参数。第一个参数是抛出的异常，第二个参数是堆栈信息。

```dart
try {
  // ···
} on Exception catch (e) {
  print('Exception details:\n $e');
} catch (e, s) {
  print('Exception details:\n $e');
  print('Stack trace:\n $s');
}
```

如果部分处理异常，同时需要再次传播，可以使用 `rethrow` 关键字。

```dart
void misbehave() {
  try {
    dynamic foo = true;
    print(foo++); // Runtime error
  } catch (e) {
    print('misbehave() partially handled ${e.runtimeType}.');
    rethrow; // Allow callers to see the exception.
  }
}

void main() {
  try {
    misbehave();
  } catch (e) {
    print('main() finished handling ${e.runtimeType}.');
  }
}
```

## finally

要确保某些代码正常运行，无论是否抛出异常，使用 `finally` 子句。 如果没有 `catch` 子句与异常匹配，则会在 `finally` 子句中运行后继续传播。

```dart
try {
  breedMoreLlamas();
} finally {
  // Always clean up, even if an exception is thrown.
  cleanLlamaStalls();
}
```

`finally` 子句在任何匹配的 `catch` 子句之后运行。

```dart
try {
  breedMoreLlamas();
} catch (e) {
  print('Error: $e'); // Handle the exception first.
} finally {
  cleanLlamaStalls(); // Then clean up.
}
```